description: setup docker for desktop
env: osx
steps:
- content: |
    # Hi There
    Bo *Bam* **Tam**  
  runner: markdown
  title: title
- file: ./scripts/dockerinstall.osx.sh
  description: This will install docker on your machine
  runner: shell
  title: Install docker
- content: |
    # Install Docker Compose
    sudo curl -L "https://github.com/docker/compose/releases/download/1.26.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    sudo chmod +x /usr/local/bin/docker-compose

    # Check Docker Compose version
    docker-compose version
  description: This will install docker-compose on your machine
  runner: shell
  title: Install docker-compose
